### ISSUE TITLE
todoの追加ページを作成

### ISSUE THREAD

**Issue by KensukeMiyata** [webfrontier-intern-20231002-20231031/todo-team-b#1]
todoタスクを追加するためのページを作成してください

**Comment by mrAkito** [comment]
Todoタスク追加、対応開始します。

**Comment by mrAkito** [comment]
## 現在の進捗
入力フォームとAPIからの一覧表示は完成。APIからの一覧表示部分はJSONPlaceHolderで代用中。

## 対応中
入力フォームと一覧表示部分が画面設計通りに配置ができない（左に寄る、もしくは両端で間が広がりすぎる）

**Comment by KensukeMiyata** [comment]
global.cssを適応したらinput textのwidth等しっかり反映されることを確認。
