### ISSUE TITLE
TodoPOSTリクエストの作成

### ISSUE THREAD

**Issue by iput2021-ono** [webfrontier-intern-20231002-20231031/todo-team-b#31]
概要
Todoの新規作成

背景
新規Todoを作成する際に必要なため

期限
なるべく早く

**Comment by mrAkito** [comment]
対応中です

**Comment by mrAkito** [comment]
`console.log(req.headers["Content-Type"])`
`req.headers["Content-Type"]`
がundefinedになるのなんで？

**Comment by mrAkito** [comment]
`headers.append("Content-Type", "application/json");`でContent-Type設定してるのに`const data = await req.json();`でJsonにわざわざ変更しないとうまく行かないのが謎

**Comment by mrAkito** [comment]
NextApiRequestこいつ何？
