### ISSUE TITLE
Todo処理におけるNEXTサーバでのAPI作成

### ISSUE THREAD

**Issue by mrAkito** [webfrontier-intern-20231002-20231031/todo-team-b#7]
## 概要
Todo部分のNEXTからFastAPIに対してGET,POST,PUT,DELETEのリクエストを発行するAPIの作成

## 背景
Todoリストアプリ作成に必要なため。Tag部分の方にも活かせるようにしたいためコンポーネントなどで、まとまっていると尚良し

## 期限
10/24（火）17:30まで

**Comment by iput2021-ono** [comment]
11時から取り掛かってます

**Comment by mrAkito** [comment]
わかりました、お願いします

**Comment by iput2021-ono** [comment]
TodoGETALL, TodoGETByIdは問題有りません
残りはページのボタンと紐づけながら引き続き制作します
