### ISSUE TITLE
Tag処理におけるNEXTサーバでのAPIの作成

### ISSUE THREAD

**Issue by KensukeMiyata** [webfrontier-intern-20231002-20231031/todo-team-b#9]
概要
Tag部分のNEXTからFastAPIに対してGET,POST,PUT,DELETEのリクエストを発行するAPIの作成

背景
Todoリストアプリ作成に必要なため。Todo部分の方にも活かせるようにしたいためコンポーネントなどで、まとまっていると尚良し

期限
10/25（水）17:30まで

**Comment by iput2021-ono** [comment]
取り掛かります

**Comment by mrAkito** [comment]
close #50 
完了したため閉じます
